---
- hosts: host
  vars_files:
    - vault.yaml
  vars:
    netname: grunniens
  tasks:
   - name: Create the network
     virt_net:
       command: define
       name: '{{ netname }}'
       xml: '{{ lookup("template", "net_grunniens.xml.j2") }}'
   - name: Ensure autostarted
     virt_net:
       autostart: yes
       name: '{{ netname }}'
   - name: Start it
     virt_net:
       command: create
       name: '{{ netname }}'
   - name: Get list of nets
     virt_net:
       command: list_nets

